quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type
quarkus.application.name=comprendia
comprendia.transcripcion.modo=whisper
comprendia.openai.api.clave=${OPENAI_API_KEY}